# Installation de l'image de base PHP 7.2

FROM php:7.2-apache

# Variable d'environnement

ENV APP_PORT=80
ENV PATH_APP="../src/"

# Copie l'application dans le containeur

# COPY ${PATH_APP} /var/www/html/
VOLUME 

# Ports de l'application

EXPOSE ${APP_PORT}/udp
EXPOSE ${APP_PORT}/tcp



